HOST = "0.0.0.0"
LOCALHOST = "127.0.0.1"
DEFAULT_PORT = 4221

END_LINE = b"\r\n"
OK = b"OK"
ECHO_PATH = b"/echo/"
FILES_PATH = b"/files/"
USER_AGENT = b"User-Agent"
CONTENT_TYPE = b"Content-Type"
CONTENT_LENGTH = b"Content-Length"
GET = b"GET"
POST = b"POST"
NOT_FOUND = b"Not Found"
GZIP = b"gzip"
